[package]
name = "rikualloc"
version = "0.1.0"
edition = "2024"

[features]
default = ["std"]
std = []

[dependencies]
libc = "0.2.178"
spin = "0.10.0"

[dev-dependencies]
libc = { version = "0.2.178", default-features = false }
